#pragma once
#include "../common/Core.h"

namespace D2Maker
{


	enum  Keys
	{
		NUL = -1,
		ZERO = GLFW_KEY_0,
		ONE = GLFW_KEY_1,
		TWO = GLFW_KEY_2,
		THREE = GLFW_KEY_3,
		FOUR = GLFW_KEY_4,
		FIVE = GLFW_KEY_5,
		SIX = GLFW_KEY_6,
		SEVEN = GLFW_KEY_7,
		EIGHT = GLFW_KEY_8,
		NINE = GLFW_KEY_9,
		SPACE = GLFW_KEY_SPACE,
		LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT,
		RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT,
		LEFT_CTR = GLFW_KEY_LEFT_CONTROL,
		RIGHT_CTR = GLFW_KEY_RIGHT_CONTROL,
		LEFT_ALT = GLFW_KEY_LEFT_ALT,
		RIGHT_ALT = GLFW_KEY_RIGHT_ALT,
		TAB = GLFW_KEY_TAB,
		CAPS = GLFW_KEY_CAPS_LOCK,
		Q = GLFW_KEY_Q,
		W = GLFW_KEY_W,
		E = GLFW_KEY_E,
		R = GLFW_KEY_R,
		T = GLFW_KEY_T,
		Y = GLFW_KEY_Y,
		U = GLFW_KEY_U,
		I = GLFW_KEY_I,
		O = GLFW_KEY_O,
		P = GLFW_KEY_P,
		A = GLFW_KEY_A,
		S = GLFW_KEY_S,
		D = GLFW_KEY_D,
		F = GLFW_KEY_F,
		G = GLFW_KEY_G,
		H = GLFW_KEY_H,
		J = GLFW_KEY_J,
		K = GLFW_KEY_K,
		L = GLFW_KEY_L,
		Z = GLFW_KEY_Z,
		X = GLFW_KEY_X,
		C = GLFW_KEY_C,
		V = GLFW_KEY_V,
		B = GLFW_KEY_B,
		N = GLFW_KEY_N,
		M = GLFW_KEY_M,
		LEFT = GLFW_MOUSE_BUTTON_LEFT,
		RIGHT = GLFW_MOUSE_BUTTON_RIGHT,


	};

}
