#pragma once
#include "../common/Core.h"

namespace D2Maker
{


	enum  Keys
	{
		NUL = -1,
		ZERO = GLFW_KEY_0,
		ONE = GLFW_KEY_1,
		TWO = GLFW_KEY_2,
		THREE = GLFW_KEY_3,
		FOUR = GLFW_KEY_4,
		FIVE = GLFW_KEY_5,
		SIX = GLFW_KEY_6,
		SEVEN = GLFW_KEY_7,
		EIGHT = GLFW_KEY_8,
		NINE = GLFW_KEY_9,
		SPACE = GLFW_KEY_SPACE,
		LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT,
		RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT,
		LEFT_CTR = GLFW_KEY_LEFT_CONTROL,
		RIGHT_CTR = GLFW_KEY_RIGHT_CONTROL,
		LEFT_ALT = GLFW_KEY_LEFT_ALT,
		RIGHT_ALT = GLFW_KEY_RIGHT_ALT,
		TAB = GLFW_KEY_TAB,
		CAPS = GLFW_KEY_CAPS_LOCK,
		Q_K = GLFW_KEY_Q,
		W_K = GLFW_KEY_W,
		E_K = GLFW_KEY_E,
		R_K = GLFW_KEY_R,
		T_K = GLFW_KEY_T,
		Y_K = GLFW_KEY_Y,
		U_K = GLFW_KEY_U,
		I_K = GLFW_KEY_I,
		O_K = GLFW_KEY_O,
		P_K = GLFW_KEY_P,
		A_K = GLFW_KEY_A,
		S_K = GLFW_KEY_S,
		D_K = GLFW_KEY_D,
		F_K = GLFW_KEY_F,
		G_K = GLFW_KEY_G,
		H_K = GLFW_KEY_H,
		J_K = GLFW_KEY_J,
		K_K = GLFW_KEY_K,
		L_K = GLFW_KEY_L,
		Z_K = GLFW_KEY_Z,
		X_K = GLFW_KEY_X,
		C_K = GLFW_KEY_C,
		V_K = GLFW_KEY_V,
		B_K = GLFW_KEY_B,
		N_K = GLFW_KEY_N,
		M_K = GLFW_KEY_M,
		LEFT = GLFW_MOUSE_BUTTON_LEFT,
		RIGHT = GLFW_MOUSE_BUTTON_RIGHT,


	};

}
